/**
 * Command Transformer
 *
 * Transforms Ensemble YAML command definitions (phases/steps/actions) into
 * Pi-compatible prompt templates written to packages/pi/prompts/.
 *
 * Output format per command:
 *   - HTML comment header with version and description
 *   - H1 title from metadata.name
 *   - Blockquote preamble from mission.summary (if present)
 *   - Fenced callout block for constraints (if present)
 *   - H2 sections for each workflow phase
 *   - H3 sections for each step with description and numbered action list
 *
 * @module ensemble-pi/transformers/command-transformer
 */

import * as path from 'path';
import { CommandYaml, Phase, Step } from '../types';

// ---------------------------------------------------------------------------
// Internal rendering helpers
// ---------------------------------------------------------------------------

/**
 * Render the HTML comment header block containing generator metadata,
 * source filename, version, and description.
 */
function renderHeader(commandYaml: CommandYaml, sourcePath: string): string {
  const { name, version, description } = commandYaml.metadata;
  const sourceFile = path.basename(sourcePath);
  const lines: string[] = [
    `<!-- Generated by ensemble-pi generator v1.0.0 | Source: ${sourceFile} -->`,
    `<!-- Command: ${name} | Version: ${version} -->`,
    `<!-- Description: ${description} -->`,
  ];
  return lines.join('\n');
}

/**
 * Render the H1 title from metadata.name.
 * Normalises "ensemble:create-prd" style names by stripping the namespace prefix
 * for display while keeping it in the title for traceability.
 */
function renderTitle(name: string): string {
  return `# ${name}`;
}

/**
 * Render mission.summary as a blockquote preamble.
 * Multi-line summaries are collapsed to a single quoted paragraph — each
 * internal newline is replaced with a space so the blockquote stays compact.
 */
function renderMission(summary: string): string {
  const collapsed = summary
    .trim()
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .join(' ');
  return `> **Mission:** ${collapsed}`;
}

/**
 * Render the constraints array as a fenced callout block.
 * Uses a blockquote with a bold header followed by bullet points.
 */
function renderConstraints(constraints: string[]): string {
  const lines: string[] = ['> **Constraints:**'];
  for (const constraint of constraints) {
    lines.push(`> - ${constraint.trim()}`);
  }
  return lines.join('\n');
}

/**
 * Coerce an action value to a display string.
 * YAML actions that contain unquoted colons are parsed by js-yaml as
 * single-key objects (e.g. `{"key": "value"}`). Reassemble them into
 * the original "key: value" text so the rendered output is readable.
 */
function actionToString(action: unknown): string {
  if (typeof action === 'string') {
    return action.trim();
  }
  if (action !== null && typeof action === 'object') {
    // Single-key object from an unquoted "key: value" action line
    const entries = Object.entries(action as Record<string, unknown>);
    if (entries.length === 1) {
      const [key, value] = entries[0];
      return `${key}: ${value}`;
    }
    // Multi-key fallback — JSON stringify is a safe last resort
    return JSON.stringify(action);
  }
  return String(action);
}

/**
 * Render a single action item.
 * Actions are numbered (1-based) and output as plain text lines.
 */
function renderAction(action: unknown, index: number): string {
  return `${index + 1}. ${actionToString(action)}`;
}

/**
 * Render a step as an H3 section with optional description and action list.
 * stepNumber is 1-based and derived from the step's position in the parent array
 * rather than `step.id` to guarantee sequential output even when YAML ids skip.
 */
function renderStep(step: Step, stepNumber: number): string {
  const parts: string[] = [];

  parts.push(`### Step ${stepNumber}: ${step.title}`);

  if (step.description && step.description.trim()) {
    parts.push('');
    parts.push(step.description.trim());
  }

  if (step.actions && step.actions.length > 0) {
    parts.push('');
    parts.push('**Actions:**');
    for (let i = 0; i < step.actions.length; i++) {
      parts.push(renderAction(step.actions[i], i));
    }
  }

  return parts.join('\n');
}

/**
 * Render a phase as an H2 section followed by its steps.
 * phaseNumber is 1-based and derived from position in the phases array.
 */
function renderPhase(phase: Phase, phaseNumber: number): string {
  const parts: string[] = [];

  parts.push(`## Phase ${phaseNumber}: ${phase.name}`);

  if (phase.steps && phase.steps.length > 0) {
    for (let i = 0; i < phase.steps.length; i++) {
      parts.push('');
      parts.push(renderStep(phase.steps[i], i + 1));
    }
  }

  return parts.join('\n');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Transform a parsed command YAML object into a Pi-compatible prompt template
 * string. Deterministic: identical input always produces identical output.
 *
 * @param commandYaml  - Parsed and validated CommandYaml object
 * @param sourcePath   - Absolute path to the source .yaml file (used in header comment)
 * @param options      - Runtime options (verbose: emit progress to stdout)
 * @returns            Rendered markdown string for the prompt template
 */
export function transformCommand(
  commandYaml: CommandYaml,
  sourcePath: string,
  options: { verbose?: boolean }
): string {
  const { name, version } = commandYaml.metadata;

  if (options.verbose) {
    process.stdout.write(`  [command-transformer] transforming: ${name} (v${version})\n`);
  }

  const sections: string[] = [];

  // 1. Header comment block
  sections.push(renderHeader(commandYaml, sourcePath));

  // 2. Title
  sections.push('');
  sections.push(renderTitle(name));

  // 3. Mission preamble (optional)
  if (commandYaml.mission?.summary) {
    sections.push('');
    sections.push(renderMission(commandYaml.mission.summary));
  }

  // 4. Constraints callout (optional)
  if (commandYaml.constraints && commandYaml.constraints.length > 0) {
    sections.push('');
    sections.push(renderConstraints(commandYaml.constraints));
  }

  // 5. Workflow phases
  const phases = commandYaml.workflow?.phases ?? [];
  for (let i = 0; i < phases.length; i++) {
    sections.push('');
    sections.push(renderPhase(phases[i], i + 1));
  }

  // Terminate with a single trailing newline for clean file output
  let output = sections.join('\n') + '\n';

  // Map AskUserQuestion → ask_user throughout the rendered output.
  // Pi uses the ask_user tool name; the Ensemble YAML sources use the
  // Claude Code tool name (AskUserQuestion).  A global replacement here
  // ensures no AskUserQuestion references survive into any Pi prompt.
  output = output.replace(/AskUserQuestion/g, 'ask_user');

  // INTERVIEW PROTOCOL annotations and {{variable}} placeholders require
  // no additional transformation: action items render verbatim (the
  // actionToString helper preserves the text as-is), and Pi shares the
  // same {{variable}} template syntax as Ensemble YAML — no escaping needed.

  return output;
}
