/**
 * Unit tests for command-transformer.ts (TRD-006-TEST)
 *
 * Covers: header, title, mission blockquote, constraints callout,
 * phase/step rendering, actionToString coercion, and AskUserQuestion → ask_user.
 */

import { transformCommand } from '../src/transformers/command-transformer';
import { CommandYaml } from '../src/types';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const MINIMAL_COMMAND: CommandYaml = {
  metadata: {
    name: 'ensemble:create-prd',
    description: 'Create a product requirements document',
    version: '1.0.0',
  },
  workflow: {
    phases: [],
  },
};

const FULL_COMMAND: CommandYaml = {
  metadata: {
    name: 'ensemble:create-prd',
    description: 'Create a product requirements document',
    version: '2.0.0',
  },
  mission: {
    summary: 'Guide the user through PRD creation.',
  },
  constraints: ['Keep responses concise', 'Use AskUserQuestion to gather input'],
  workflow: {
    phases: [
      {
        id: 1,
        name: 'Discovery',
        steps: [
          {
            id: 1,
            title: 'Gather Requirements',
            description: 'Collect all necessary data from the user.',
            actions: [
              'Review existing documents',
              { 'AskUserQuestion: What is the target user?': null },
              'Summarize findings',
            ],
          },
          {
            id: 2,
            title: 'Define Scope',
            description: '',
            actions: [],
          },
        ],
      },
      {
        id: 2,
        name: 'Drafting',
        steps: [
          {
            id: 1,
            title: 'Write Draft',
            description: 'Produce the first draft.',
            actions: ['Draft section 1'],
          },
        ],
      },
    ],
  },
};

const SOURCE_PATH = '/workspace/packages/development/commands/create-prd.yaml';

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('transformCommand', () => {
  describe('HTML comment header', () => {
    it('starts with the generator comment', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).toMatch(/^<!-- Generated by ensemble-pi generator/);
    });

    it('includes the source filename in the header', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('Source: create-prd.yaml');
    });

    it('includes the command name and version in the second comment line', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('Command: ensemble:create-prd | Version: 1.0.0');
    });

    it('includes the description in the third comment line', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('Description: Create a product requirements document');
    });
  });

  describe('H1 title', () => {
    it('renders the metadata name as an H1 heading', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('# ensemble:create-prd');
    });

    it('uses the name from metadata when it differs', () => {
      const cmd: CommandYaml = {
        ...MINIMAL_COMMAND,
        metadata: { ...MINIMAL_COMMAND.metadata, name: 'ensemble:custom-command' },
      };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      expect(output).toContain('# ensemble:custom-command');
    });
  });

  describe('mission blockquote', () => {
    it('emits a blockquote when mission.summary is present', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('> **Mission:**');
    });

    it('includes the mission summary text in the blockquote', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('Guide the user through PRD creation.');
    });

    it('does NOT emit a blockquote when mission is absent', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).not.toContain('> **Mission:**');
    });

    it('collapses multi-line summary into a single blockquote', () => {
      const cmd: CommandYaml = {
        ...MINIMAL_COMMAND,
        mission: { summary: 'Line one.\nLine two.\nLine three.' },
      };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      const blockquote = output
        .split('\n')
        .find((l) => l.startsWith('> **Mission:**'));
      expect(blockquote).toBeDefined();
      // All text should be on one line (no continuation lines with ">")
      const missionLines = output.split('\n').filter((l) => l.startsWith('>'));
      expect(missionLines).toHaveLength(1);
    });
  });

  describe('constraints callout', () => {
    it('emits a constraints block when constraints array is present', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('> **Constraints:**');
    });

    it('renders each constraint as a bullet under the callout header', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('> - Keep responses concise');
    });

    it('does NOT emit a constraints block when constraints are absent', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).not.toContain('> **Constraints:**');
    });

    it('does NOT emit a constraints block when constraints array is empty', () => {
      const cmd: CommandYaml = { ...MINIMAL_COMMAND, constraints: [] };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      expect(output).not.toContain('> **Constraints:**');
    });
  });

  describe('phases rendered as H2', () => {
    it('renders each phase as an H2 heading with 1-based number', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('## Phase 1: Discovery');
      expect(output).toContain('## Phase 2: Drafting');
    });

    it('does not emit any H2 when there are no phases', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output).not.toMatch(/^## Phase/m);
    });
  });

  describe('steps rendered as H3', () => {
    it('renders each step as an H3 heading with 1-based number', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('### Step 1: Gather Requirements');
      expect(output).toContain('### Step 2: Define Scope');
    });

    it('resets step numbering per phase', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('### Step 1: Write Draft');
    });

    it('includes step description when present and non-empty', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('Collect all necessary data from the user.');
    });

    it('does not emit a blank description when step.description is empty', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      // "Define Scope" has empty description — ensure no double blank lines from it
      // and that the next step heading still appears
      expect(output).toContain('### Step 2: Define Scope');
    });

    it('renders numbered actions under **Actions:**', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).toContain('**Actions:**');
      expect(output).toContain('1. Review existing documents');
      expect(output).toContain('3. Summarize findings');
    });
  });

  describe('actionToString — object coercion', () => {
    it('renders a single-key YAML-parsed object as "key: value"', () => {
      const cmd: CommandYaml = {
        ...MINIMAL_COMMAND,
        workflow: {
          phases: [
            {
              id: 1,
              name: 'Test Phase',
              steps: [
                {
                  id: 1,
                  title: 'Test Step',
                  actions: [{ 'someKey': 'someValue' }],
                },
              ],
            },
          ],
        },
      };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      expect(output).toContain('someKey: someValue');
      expect(output).not.toContain('[object Object]');
    });

    it('renders a string action verbatim', () => {
      const cmd: CommandYaml = {
        ...MINIMAL_COMMAND,
        workflow: {
          phases: [
            {
              id: 1,
              name: 'Test Phase',
              steps: [
                {
                  id: 1,
                  title: 'Test Step',
                  actions: ['Do something specific'],
                },
              ],
            },
          ],
        },
      };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      expect(output).toContain('Do something specific');
    });

    it('renders a multi-key object as JSON (fallback)', () => {
      const cmd: CommandYaml = {
        ...MINIMAL_COMMAND,
        workflow: {
          phases: [
            {
              id: 1,
              name: 'Test Phase',
              steps: [
                {
                  id: 1,
                  title: 'Test Step',
                  actions: [{ key1: 'v1', key2: 'v2' }],
                },
              ],
            },
          ],
        },
      };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      expect(output).toContain('key1');
      expect(output).not.toContain('[object Object]');
    });
  });

  describe('AskUserQuestion → ask_user replacement', () => {
    it('replaces AskUserQuestion in action strings', () => {
      const cmd: CommandYaml = {
        ...MINIMAL_COMMAND,
        workflow: {
          phases: [
            {
              id: 1,
              name: 'Interview',
              steps: [
                {
                  id: 1,
                  title: 'Ask user',
                  actions: ['Use AskUserQuestion to get info'],
                },
              ],
            },
          ],
        },
      };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      expect(output).toContain('ask_user');
      expect(output).not.toContain('AskUserQuestion');
    });

    it('replaces AskUserQuestion in object-coerced action values', () => {
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      // FULL_COMMAND has { 'AskUserQuestion: What is the target user?': null }
      expect(output).not.toContain('AskUserQuestion');
      expect(output).toContain('ask_user');
    });

    it('replaces AskUserQuestion in constraint strings', () => {
      // FULL_COMMAND constraint: 'Use AskUserQuestion to gather input'
      const output = transformCommand(FULL_COMMAND, SOURCE_PATH, {});
      expect(output).not.toContain('AskUserQuestion');
    });
  });

  describe('empty tools / minimal command', () => {
    it('does not emit a blockquote when mission is absent', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      // Use the specific blockquote marker rather than bare ">" (HTML comments contain "-->")
      expect(output).not.toContain('> **Mission:**');
      expect(output).not.toContain('> **Constraints:**');
    });

    it('does not emit **Actions:** when step has no actions', () => {
      const cmd: CommandYaml = {
        ...MINIMAL_COMMAND,
        workflow: {
          phases: [
            {
              id: 1,
              name: 'Phase',
              steps: [{ id: 1, title: 'Step with no actions' }],
            },
          ],
        },
      };
      const output = transformCommand(cmd, SOURCE_PATH, {});
      expect(output).not.toContain('**Actions:**');
    });

    it('terminates with a trailing newline', () => {
      const output = transformCommand(MINIMAL_COMMAND, SOURCE_PATH, {});
      expect(output.endsWith('\n')).toBe(true);
    });
  });

  describe('verbose option', () => {
    it('writes progress to stdout when verbose is true', () => {
      const writeSpy = jest.spyOn(process.stdout, 'write').mockImplementation(() => true);
      transformCommand(MINIMAL_COMMAND, SOURCE_PATH, { verbose: true });
      expect(writeSpy).toHaveBeenCalledWith(
        expect.stringContaining('ensemble:create-prd')
      );
      writeSpy.mockRestore();
    });

    it('does not write to stdout when verbose is false', () => {
      const writeSpy = jest.spyOn(process.stdout, 'write').mockImplementation(() => true);
      transformCommand(MINIMAL_COMMAND, SOURCE_PATH, { verbose: false });
      expect(writeSpy).not.toHaveBeenCalled();
      writeSpy.mockRestore();
    });
  });
});
